spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pg
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect